names = ['Baseball Pitch',
 'Basketball',
 'BenchPress',
 'Biking',
 'Billiards',
 'BreastStroke',
 'Clean_Jerk',
 'Diving',
 'Drumming',
 'Fencing',
 'Golf Swing',
 'High Jump',
 'Horse Race',
 'Horse Riding',
 'Hula Hoop',
 'Javelin Throw',
 'Juggling Balls',
 'Jump Rope',
 'Jumping Jack',
 'Kayaking',
 'Lunges',
 'Military Parade',
 'Mixing',
 'Nunchucks',
 'Pizza Tossing',
 'Playing Guitar',
 'Playing Piano',
 'Playing Tabla',
 'Playing Violin',
 'Pole Vault',
 'Pommel Horse',
 'Pull Ups',
 'Punch',
 'Push Ups',
 'Rock Climbing Indoor',
 'Rope Climbing',
 'Rowing',
 'Salsa Spin',
 'Skateboarding',
 'Skiing',
 'Skijet',
 'Soccer Juggling',
 'Swing',
 'TaiChi',
 'Tennis Swing',
 'Throw Discus',
 'Trampoline Jumping',
 'Volleyball Spiking',
 'Walking With Dog',
 'YoYo']