{
 "title": "Detected humans amount",
 "time": { "from": "2024-12-07T18:49:32.369Z", "to": "2024-12-07T18:49:42.390Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Mood of the crowd",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT face, COUNT(*)\nFROM object_detection \nGROUP BY face"
    }
   ]
  },
  {
   "title": "Amount of human",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "-- SELECT COUNT(DISTINCT(object_id_idx)), time_updated \n-- FROM object_detection_idx \n-- GROUP BY time_updated\n-- ORDER BY time_updated\n\nSELECT time_updated, total_obj AS \"Total humans\" FROM object_detection_idx \n\n\n\n"
    }
   ]
  },
  {
   "title": "Race groups",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT race, COUNT(*)\nFROM object_detection\nGROUP BY race"
    }
   ]
  },
  {
   "title": "Age groups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT age_category AS category, \nCOUNT(*) AS count\nFROM object_detection \nGROUP BY age_category"
    }
   ]
  },
  {
   "title": "Gender groups",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gender, COUNT(*)\nFROM object_detection \nGROUP BY gender"
    }
   ]
  }
 ]
}